### ISSUE TITLE
Xcode 9.4 build issues

### ISSUE THREAD

**Issue by stelford** [sroddy/flutter_string_encryption#7]
Hello.
I am having real troubles getting this to work with Xcode 9.4.1 on an imported flutter app. I built it on Android and linux first, and then wanted to build the ios version on my mac. I imported and started the debug and it seemed okay until I hit this;

```Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
Could not build the application for the simulator.
```

so no problem, I edited my Podfile and added in 

```post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

However, when I then do a debug build, I get the following

```/Users/stef/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_string_encryption-0.0.2/ios/Classes/FlutterStringEncryptionPlugin.m:2:9: fatal error: 'flutter_string_encryption/flutter_string_encryption-Swift.h' file not found
    #import <flutter_string_encryption/flutter_string_encryption-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.
Could not build the application for the simulator.```

Any ideas what I am missing or doing wrong are gratefully received.

**Comment by sroddy** [comment]
Hi,
can you please try with Swift version 4.0 instead of 3.0 and tell me if it works?
Thanks a lot

**Comment by stelford** [comment]
sadly no, it's the same error if I change the Podfile to 
```      config.build_settings['SWIFT_VERSION'] = '4.0'```

looking at ; https://stackoverflow.com/questions/40484816/modulename-swift-h-file-not-found-in-xcode8 it seems to suggest that it's some build option inside the module.. but.. I am not an iOS dev by a long stretch so this reads mostly as greek to me (sorry!!)

**Comment by ChrisHoffmann96** [comment]
Is there any fix to this yet? Encountered the same problem here

**Comment by sroddy** [comment]
Hi,
are you using the `use_frameworks!` flag inside your Podfile?

**Comment by yahya31415** [comment]
I am getting the same error in Xcode Version 9.2. I added `use_frameworks!` to my Podfile and set the Swift version to 4.0. 
This is the error:
`<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/flutter_string_encryption-umbrella.h"
        ^
/Users/............/ios/Pods/Target Support Files/flutter_string_encryption/flutter_string_encryption-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_string_encryption': '/Users/........./flutter/.pub-cache/hosted/pub.dartlang.org/flutter_string_encryption-0.1.0/ios/Classes/FlutterStringEncryptionPlugin.h'
#import "FlutterStringEncryptionPlugin.h"
        ^
<unknown>:0: error: could not build Objective-C module 'flutter_string_encryption'`

**Comment by josep-albert-bonarea** [comment]
Same here:



Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/sergi/flutter_dietes/ios/Pods/SCrypto/Source/SCrypto.swift:107:111: warning: using '!' is not allowed here; treating this as '?' instead
            typealias Function = (_ data: UnsafeRawPointer, _ len: CC_LONG, _ md: UnsafeMutablePointer<UInt8>) -> UnsafeMutablePointer<UInt8>!
                                                                                                                  ^                          ~
                                                                                                                                             ?
    === BUILD TARGET flutter_string_encryption OF PROJECT Pods WITH CONFIGURATION Debug ===
    While building module 'Flutter' imported from /Users/sergi/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_string_encryption-0.2.0/ios/Classes/FlutterStringEncryptionPlugin.h:1:
    In file included from <module-includes>:1:
    In file included from /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/Flutter.h:44:
    In file included from /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    In file included from /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterPlugin.h:13:
    /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterPlatformViews.h:25:11: warning: parameter 'viewIdentifier' not found in the function declaration [-Wdocumentation]
     * @param viewIdentifier A unique identifier for this `UIView`.
              ^~~~~~~~~~~~~~
    /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterPlatformViews.h:26:11: warning: parameter 'arguments' not found in the function declaration [-Wdocumentation]
     * @param arguments Parameters for creating the `UIView` sent from the Dart side of the Flutter app.
              ^~~~~~~~~
    While building module 'Flutter' imported from /Users/sergi/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_string_encryption-0.2.0/ios/Classes/FlutterStringEncryptionPlugin.h:1:
    In file included from <module-includes>:1:
    In file included from /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/Flutter.h:44:
    In file included from /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterPlugin.h:213:11: warning: parameter 'factoryId::' not found in the function declaration [-Wdocumentation]
     * @param factoryId:: A unique identifier for the factory, the Dart code of the Flutter app can use
              ^~~~~~~~~~~
    /Users/sergi/flutter_dietes/ios/Pods/../.symlinks/flutter/ios/Flutter.framework/Headers/FlutterPlugin.h:213:11: note: did you mean 'factoryId'?
     * @param factoryId:: A unique identifier for the factory, the Dart code of the Flutter app can use
              ^~~~~~~~~~~
              factoryId
    3 warnings generated.
    /Users/sergi/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_string_encryption-0.2.0/ios/Classes/FlutterStringEncryptionPlugin.m:2:9: fatal error: 'flutter_string_encryption/flutter_string_encryption-Swift.h' file not found
    #import <flutter_string_encryption/flutter_string_encryption-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings and 1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.

**Comment by baki83** [comment]
Regarding the last error here from **josepalbert95**, you may try this :

- make sure your create a fresh, empty Flutter project with the Swift support **ON MAC** (you choose this when you create the project in Android Studio). If you created the project on Windows, this error will still show.
- copy pubspec.yaml, everything from lib folder and any other directories and files your project needs into the new freshly created project on MAC
- open ios/workspace file in XCode and set your signing info - and everything else necessary
- edit Podspec inside iOS dir and just uncomment "platform :ios, '9.0'". No need to change anything else
- connect your device/emulator and type "flutter run" - it should work

Tried on latest Catalina 10.15 and latest XCode 11.3.1
